<?php
/**
 * Project helper functions.
 * Generated by: php artisan make:helper
 */
if (! function_exists('currency_symbol')) {
    /**
     * Return a basic currency symbol for a given code.
     */
    function currency_symbol(?string $code): string
    {
        return match (strtoupper($code ?? 'GBP')) {
            'GBP' => '£', 'USD' => '$', 'EUR' => '€',
            default => ''
        };
    }
}

if (! function_exists('catalog_url')) {
    /**
     * Build the catalog URL with query params.
     * Example: catalog_url(['category_slug' => ['gold-bars']])
     */
    function catalog_url(array $params = []): string
    {
        return route('ext.catalog', $params);
    }
}

if (! function_exists('getCategories')) {
    function getCategories(\App\Services\ExternalProductsService $svc, \App\Services\PricingService $pricing) {
        return $svc->fetchCategories();
    }
}

if (! function_exists('getWeughtOption')) {
    function getWeughtOption(\App\Services\ExternalProductsService $svc, \App\Services\PricingService $pricing) {
        return  $svc->fetchWeightOptions();
    }
}

if (! function_exists('getBrand')) {
    function getBrand(\App\Services\ExternalProductsService $svc, \App\Services\PricingService $pricing) {
        return  $svc->fetchBrands();
    }
}
if (! function_exists('homeservices')) {
    function homeservices() {
       $result_home_services = DB::table('home_services')->orderBy('sort_order', 'asc')->get();
       return $result_home_services;
    }
}
